title: <p align="center"> Putri Nurdianti </p>

logo: "/images/logo.jpg?raw=true"

description:
  <p align="center">
  <a href="Putri Nurdianti-CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/putri-nurdianti-8404891a7/">LinkedIn</a> |
  <a href="https://github.com/putrinurdianti">GitHub</a>
  </p>
  
  <p align="justify">
  Bachelor of Statistics from Institut Teknologi Sepuluh Nopember. 
  <br><br>
  I am a fresh graduate from Statistics Department at Institut Teknologi Sepuluh Nopember. Through my college years, I have experiences in data analysis using various statistical methods with software such as Microsoft Excel, R, SPSS, Minitab, and Python. I also have some experiences in using SQL and Google Data Studiio to analyze and visualize data from the bootcamp I have attended. From my internships experiences, I have abilities in creating dashboards and automated reports using Google Spreadsheet. During my college years, I also participated in several organizations and volunteers where I built my skills in teamwork, leadership, time management, and communication.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
